### ISSUE TITLE
Orchestration release checklist

### ISSUE THREAD

**Issue by Cedev** [a10networks/a10-neutron-lbaas#296]
Deployment checklist
====================
​
- [ ] Move all CLI stuff to new package (public and private), a10-neutronclient
- [ ] Tests for CLI.
- [ ] Install docs
- [ ] Usage docs
​
- [ ] Move all UI stuff to new pacakge (public and private), a10-horizon
- [ ] Tests for GUI (write test plan, have Chelsea or Kristina execute)
- [ ] Install docs
- [ ] Usage docs
​
- [ ] All public extensions, hooks, and filters into a10-neutron-lbaas
- [ ] Full test coverage?
- [ ] Install docs
- [ ] Usage docs
​

**Comment by mdurrant-b3** [comment]
[TestsTemplate.xls.zip](https://github.com/a10networks/a10-neutron-lbaas/files/217875/TestsTemplate.xls.zip)
